### ISSUE TITLE
How to add kdtree support?

### ISSUE THREAD

**Issue by IrinaZhuang** [UTS-CAS/SDF_cuda#1]
Could you giving a version that is using kdtree? Or could you please telling me how to add kdtree support into cuda code? I'm really new to cuda.

**Comment by rFalque** [comment]
Hi @IrinaZhuang. Unfortunately, you cannot get a perfect SDF using a kdtree. For example, if there is a very large triangle a multitude of small ones, the large triangle would be unlikely to be picked from the kdtree as it would be summarized by a single point.

In the case where all triangles have a similar size, it can actually work (it works best if you use the centroid of the triangle and the triangle normal for the sign). I have it implemented on CPU there: [https://github.com/rFalque/voxelization_and_sdf](https://github.com/rFalque/voxelization_and_sdf)

If you really want to go with a kdtree on cuda for SDF, you can have a look at that other repository: [https://github.com/RaviHastantram/GPU-Kd-Tree](https://github.com/RaviHastantram/GPU-Kd-Tree)

**Comment by rFalque** [comment]
Closing issue
